### ISSUE TITLE
Can't access textField:shouldChangeCharactersIn:range:

### ISSUE THREAD

**Issue by hpbl** [Serheo/PhoneNumberFormatter#3]
Hi, This pod has been really useful, but I wanted to implement something that does not seem to be possible the way it is now.

I'd like for when the user has finished inputing his phone number, to automatically enable a button. The only solution I came up with was doing that on `textField:shouldChangeCharactersIn:range:`, but this method is already implemented by `FormattedTextFieldDelegate`, and there it makes no use of the `userDelegate` property.

Is there a way I could implement the behavior I want with the pod?

Thanks.

**Comment by AlexGee17** [comment]
Any updates on this issue? SHSPhoneComponent does implement this method correctly, though, but we would love to have this behavior in Swift version as well!

**Comment by hpbl** [comment]
@AlexGee17  I actually gave up on this feature, but I'll give it a go at forking this repo and making a PR with a solution.
