### ISSUE TITLE
Wrong complete phoneNumber

### ISSUE THREAD

**Issue by VMavrin** [Serheo/PhoneNumberFormatter#5]
If prefix has a non digit symbols (ex: "+7"), so the phoneNumber method return string without "+" symbol.

**Comment by VMavrin** [comment]
And one more. Prefix can contain whitespaces on ends (ex: "+7 "), so complete phone number should trim whitespaces.

**Comment by Serheo** [comment]
phoneNumber() and phoneNumberWithoutPrefix() methods works correctly.
First returns only digits, second one - only digits from base part of the number(without prefix)
